0.1 Draft
Anarmard/java-explore-with-me pull request #3
Opened 2023-06-09 00:46 UTC by Anarmard

Александр, привет. Это моя первая версия сервиса статистики дипломного проекта. 
Есть проблема с клиентом сервиса статистики, не считываются следующие данные в StatsClient (выделил жирным):
    public StatsClient(@Value(**"ewm-main-service")** String application,
                       @Value(**"http://localhost:9090"**) String statsServiceUri,
                       ObjectMapper json) {
        this.application = application;
        this.statsServiceUri = statsServiceUri;
        this.json = json;
        this.httpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(2))
                .build();
    } 

Вдруг ты сразу поймешь, где у меня ошибка.
Идею реализации взял с семинара и додумал, надеюсь верно.

2023-06-09 17:37 UTC, alexache requested changes

2023-06-09 17:37 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/ewm/client/stats/StatsClient.java
> +    public StatsClient(@Value("ewm-main-service") String application,
Это не та аннотация @Value. Должна быть не ломбока, а спринга

2023-06-10 20:43 UTC, alexache requested changes

2023-06-10 20:43 UTC, alexache commented on main-service/src/main/resources/application.properties
> +db.name=ewm
Как-то на вид намешано разных пропертей и харкода их

2023-06-10 20:43 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/ewm/client/stats/StatsClient.java
> +    public void hit(HttpServletRequest userRequest) {
Какой-то не очень однозначный аргумент, может передавать только отдельные требуемые аргументы?

2023-06-10 20:43 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/repository/StatsRepository.java
> +    public StatsRepository(JdbcTemplate jdbcTemplate) {
А где-то через @RequiredArgeConstructor? Стоит придерживаться одного подхода

2023-06-10 20:43 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/service/StatsServiceImpl.java
> +        if (uris == null || uris.isEmpty()) {
Закомментированный код лучше подчищать

2023-06-10 20:43 UTC, alexache commented on stats/stats-server/src/main/resources/schema.sql
> +    ip      VARCHAR(15)                 NOT NULL,
А если ipv6 придет? Не стоит слишком ограничивать

2023-06-13 11:27 UTC, Anarmard commented on main-service/src/main/resources/application.properties
> +db.name=ewm
Поправил, убрал лишнее. Но возможно что-то еще осталось.

2023-06-13 11:36 UTC, Anarmard commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/service/StatsServiceImpl.java
> +        if (uris == null || uris.isEmpty()) {
Извини, ты уже делал такой комментарий. Убрал

2023-06-13 11:39 UTC, Anarmard commented on stats/stats-server/src/main/resources/schema.sql
> +    ip      VARCHAR(15)                 NOT NULL,
Хорошо, спасибо! Поставил 255, чтобы было однообразно.

2023-06-13 11:49 UTC, Anarmard commented on stats/stats-client/src/main/java/ru/practicum/ewm/client/stats/StatsClient.java
> +    public void hit(HttpServletRequest userRequest) {
Александр, извини, пока не понимаю как сделать лучше. Я взял этот аргумент из описания задачи, там была следующая подсказка, как определять ip запроса:
@GetMapping("/some/path/{id}")
public void logIPAndPath(@PathVariable long id, **HttpServletRequest request**) {
    log.info("client ip: {}", **request**.getRemoteAddr());
    log.info("endpoint path: {}", **request**.getRequestURI());
}

2023-06-13 15:32 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/ewm/client/stats/StatsClient.java
> +    public void hit(HttpServletRequest userRequest) {
я именно про то, что можно передать айпи и URI в метод клиента отдельными аргументами, на основе свойств этого реквеста

2023-06-13 15:33 UTC, alexache approved these changes

2023-06-13 22:56 UTC, merged