1.0 First version main_svc
Anarmard/java-explore-with-me pull request #4
Opened 2023-06-19 01:54 UTC by Anarmard

Есть ошибки в коде, необходимо поправить

2023-06-20 19:02 UTC, alexache requested changes

2023-06-20 19:02 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/event/EventServiceImpl.java
> +                                               HttpServletRequest request) {
для чего используется request?

2023-06-20 22:22 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/event/EventServiceImpl.java
> +                                               HttpServletRequest request) {
Вот и я сейчас думаю, зачем здесь это.. Это же админ запрашивает, такой запрос не должен уходить в статистику. Убрал этот параметр отсюда вообще. Спасибо!

2023-06-20 23:04 UTC, Anarmard commented on main-service/pom.xml
> +            <version>1.5.3.Final</version>
Понял, перенес в родительский пом.

2023-06-20 23:07 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/AdmEventController.java
> +        return eventService.getEventsByAdmin(userIdList, states, categories, rangeStart, rangeEnd, from, size, request);
Ясно. Конкретно в эндпоинте этот параметр вообще не нужен (как ты верно отметил). Но в других поправил.

2023-06-20 23:27 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/AdmEventController.java
> +        return eventService.getEventsByAdmin(userIdList, states, categories, rangeStart, rangeEnd, from, size, request);
Cпасибо, вроде получилось!

2023-06-20 23:28 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/pub/PubEventController.java
> +    @ResponseStatus(HttpStatus.OK)
ОК, понял.

2023-06-20 23:49 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/AdmUserController.java
> +                                     @RequestParam(defaultValue = "0") Integer from,
Добавил во всех контроллерах валидацию @PositiveOrZero and @Positive
Спасибо!

2023-06-20 23:54 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +    String name;
Извини. Я почему-то проигнорил все эти ограничения из спецификации. Поправил.

2023-06-20 23:57 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/compilation/CompilationDto.java
> +    String title;
Добавил

2023-06-21 00:01 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/category/NewCategoryDto.java
> +    String name;
Done!

2023-06-21 00:02 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/compilation/NewCompilationDto.java
> +    String title;
OK

2023-06-21 00:06 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/compilation/UpdateCompilationRequest.java
> +    String title;
В dto, которое для обновления данных, какую валидацию следует поставить? 
В остальных дто я ставил валидацию, что поле не пустое. Здесь любое поле может быть пустым - значит данное поле не обновляем.

2023-06-21 00:11 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/event/NewEventDto.java
> +    String description;
Done

2023-06-21 00:22 UTC, Anarmard commented on main-service/src/main/resources/schema.sql
> +    confirmed_requests  BIGINT,
Хорошо, удалил

2023-06-21 00:22 UTC, Anarmard commented on main-service/src/main/resources/schema.sql
> +    views               BIGINT,
Ок, спасибо, удалил

2023-06-21 00:24 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    Long confirmedRequests; // Количество одобренных заявок на участие в данном событии
Понял, надо считать из таблицы Requests.

2023-06-21 00:25 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    Long views; // Количество просмотрев события
А это поле тогда из таблицы Stats

2023-06-21 00:29 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/event/EventServiceImpl.java
> +    private void updateEventEntity(UpdateEventUserRequest event, Event eventToUpdate) {
Переместил их вниз. Спасибо!

2023-06-21 00:33 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/repository/RequestRepository.java
> +    @Query("select r from Request r " +
Александр, я если честно не люблю SQL запросы писать, тяжело идут. Но тут я не смог через именование метода учесть условие, что Пользователь выгружает все события кроме своих.

2023-06-21 01:27 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/request/RequestServiceImpl.java
> +        Optional<Request> requestFromDb = requestRepository.findByRequesterIdAndEventId(userId, eventId);
Да, конечно! Спасибо!

2023-06-21 01:40 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/request/RequestServiceImpl.java
> +        List<Request> requestList = requestIdList.stream().map((id) -> requestRepository.findById(id)
Да, спасибо! Поправил!

2023-06-21 01:59 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/request/RequestServiceImpl.java
> +                event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Понял, спасибо! поправил

2023-06-21 02:16 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/dto/event/NewEventDto.java
> +    Location location;
Добавил LocationDto

2023-06-29 19:41 UTC, alexache approved these changes

2023-06-29 19:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/controller/priv/PrivateRequestController.java
> +                userId + requestId);
Лучше логгировать через плейсхолдеры, то есть log.info("Some id {} of the user {}", id, userId);

2023-06-29 19:41 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/service/StatsServiceImpl.java
> +            log.info("StatsService / calculateViews / start / end: " + sdf.parse(end) + sdf.parse(start));
Не стоит делать какие-то вычисления или конвертации только ради логгирования

2023-06-30 21:58 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/priv/PrivateRequestController.java
> +                userId + requestId);
Ок, понял. Поменяю это на следующем этапе диплома.

2023-06-30 21:58 UTC, Anarmard commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/service/StatsServiceImpl.java
> +            log.info("StatsService / calculateViews / start / end: " + sdf.parse(end) + sdf.parse(start));
Ок, поправлю это. Спасибо!

2023-06-30 21:59 UTC, merged