1.0 first version (add comments)
Anarmard/java-explore-with-me pull request #5
Opened 2023-07-01 15:22 UTC by Anarmard

2023-07-03 12:25 UTC, alexache requested changes

2023-07-03 12:25 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/controller/priv/PrivateCommentController.java
> +
А можно ли обновлять комментарий?

2023-07-03 12:25 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        commentToSave.setCommentator(userRepository.findById(userId).get());
Проще сделать User user = userRepository.findById(userId).orElseThrow() нежели делать 2 запроса

2023-07-03 12:25 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        if (userId.equals(commentRepository.findById(commentId).get().getCommentator().getId())) {
Может ли админ удалять комментарии? Может ли пользователь и админ редактировать комментарий?

2023-07-03 12:25 UTC, alexache commented on postman/feature.json
> +}
Не помешает побольше сценариев - попытка изменить чужой комментарий, и так далее

2023-07-03 20:20 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/admin/AdmEventController.java
> +                updateEventAdminRequest.toString());
Понял, поправил!

2023-07-03 20:21 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/controller/priv/PrivateCommentController.java
> +
Да, наверное надо, чтобы пользователь мог обновлять свой комментарий. Сейчас добавлю! Спасибо!

2023-07-03 20:22 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        commentToSave.setCommentator(userRepository.findById(userId).get());
orElseThrow() - точно! спасибо, переделал

2023-07-03 20:32 UTC, Anarmard commented on main-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        if (userId.equals(commentRepository.findById(commentId).get().getCommentator().getId())) {
Да, админ должен уметь удалять комментарий - верно. Добавлю. Редактировать комментарий, я думаю, может только пользователь. Если админу не нравится комментарий, то он удаляет его)

2023-07-03 21:11 UTC, Anarmard commented on postman/feature.json
> +}
Хорошо, добавлю на ошибки

2023-07-04 10:24 UTC, alexache approved these changes

2023-07-07 17:30 UTC, merged